-- Inventory & Stock Management System — initial schema.
--
-- Design note: on-hand quantity is never a directly editable column. It is derived
-- from the append-only stock_movements ledger and materialised into product_stock
-- by a trigger, so the summary can never drift from the ledger.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255),
    role          VARCHAR(20)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'STAFF'))
);

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    deleted_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

-- Name is unique among live rows only, so a soft-deleted name can be reused.
CREATE UNIQUE INDEX uq_categories_name_live ON categories (lower(name)) WHERE deleted_at IS NULL;

CREATE TABLE suppliers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(160) NOT NULL,
    contact_email VARCHAR(255),
    contact_phone VARCHAR(40),
    address       VARCHAR(500),
    deleted_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255)
);

CREATE UNIQUE INDEX uq_suppliers_name_live ON suppliers (lower(name)) WHERE deleted_at IS NULL;

CREATE TABLE products (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku           VARCHAR(64)  NOT NULL,
    name          VARCHAR(200) NOT NULL,
    description   TEXT,
    unit_price    NUMERIC(12, 2) NOT NULL DEFAULT 0,
    reorder_level INTEGER      NOT NULL DEFAULT 0,
    category_id   BIGINT       REFERENCES categories (id),
    supplier_id   BIGINT       REFERENCES suppliers (id),
    deleted_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    CONSTRAINT ck_products_unit_price CHECK (unit_price >= 0),
    CONSTRAINT ck_products_reorder_level CHECK (reorder_level >= 0)
);

CREATE UNIQUE INDEX uq_products_sku_live ON products (upper(sku)) WHERE deleted_at IS NULL;
CREATE INDEX ix_products_category ON products (category_id);
CREATE INDEX ix_products_supplier ON products (supplier_id);
CREATE INDEX ix_products_name ON products (lower(name));

CREATE TABLE product_images (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   BIGINT       NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    -- S3 object key only. Never store a rendered URL: URLs are presigned at read time.
    object_key   VARCHAR(512) NOT NULL,
    content_type VARCHAR(120),
    size_bytes   BIGINT,
    is_primary   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by   VARCHAR(255),
    CONSTRAINT uq_product_images_key UNIQUE (object_key)
);

CREATE INDEX ix_product_images_product ON product_images (product_id);
-- At most one primary image per product.
CREATE UNIQUE INDEX uq_product_images_primary ON product_images (product_id) WHERE is_primary;

CREATE TABLE stock_movements (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT      NOT NULL REFERENCES products (id),
    movement_type  VARCHAR(10) NOT NULL,
    -- Signed delta applied to on-hand quantity: IN > 0, OUT < 0, ADJUST either way.
    quantity_delta INTEGER     NOT NULL,
    reason         VARCHAR(255),
    reference      VARCHAR(120),
    occurred_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by     VARCHAR(255),
    CONSTRAINT ck_stock_movements_type CHECK (movement_type IN ('IN', 'OUT', 'ADJUST')),
    CONSTRAINT ck_stock_movements_delta CHECK (
        quantity_delta <> 0
        AND (movement_type <> 'IN' OR quantity_delta > 0)
        AND (movement_type <> 'OUT' OR quantity_delta < 0)
    )
);

CREATE INDEX ix_stock_movements_product ON stock_movements (product_id, occurred_at DESC);

-- Materialised on-hand quantity. Written only by the trigger below.
CREATE TABLE product_stock (
    product_id BIGINT PRIMARY KEY REFERENCES products (id) ON DELETE CASCADE,
    quantity   INTEGER     NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_product_stock_non_negative CHECK (quantity >= 0)
);

CREATE TABLE attachments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type   VARCHAR(40)  NOT NULL,
    entity_id     BIGINT       NOT NULL,
    object_key    VARCHAR(512) NOT NULL,
    original_name VARCHAR(255),
    content_type  VARCHAR(120),
    size_bytes    BIGINT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    VARCHAR(255),
    CONSTRAINT uq_attachments_key UNIQUE (object_key),
    CONSTRAINT ck_attachments_entity_type CHECK (entity_type IN ('PRODUCT', 'STOCK_MOVEMENT', 'SUPPLIER'))
);

CREATE INDEX ix_attachments_entity ON attachments (entity_type, entity_id);

-- Every product gets a stock row at creation so joins never have to be outer joins.
CREATE OR REPLACE FUNCTION create_product_stock_row() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO product_stock (product_id, quantity) VALUES (NEW.id, 0);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_products_create_stock
    AFTER INSERT ON products
    FOR EACH ROW EXECUTE FUNCTION create_product_stock_row();

-- The ledger is the source of truth; this keeps the summary in step within the
-- same transaction. The CHECK on product_stock.quantity rejects oversell here.
CREATE OR REPLACE FUNCTION apply_stock_movement() RETURNS TRIGGER AS $$
BEGIN
    UPDATE product_stock
       SET quantity = quantity + NEW.quantity_delta,
           updated_at = now()
     WHERE product_id = NEW.product_id;

    IF NOT FOUND THEN
        INSERT INTO product_stock (product_id, quantity)
        VALUES (NEW.product_id, NEW.quantity_delta);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_stock_movements_apply
    AFTER INSERT ON stock_movements
    FOR EACH ROW EXECUTE FUNCTION apply_stock_movement();

-- The ledger is append-only.
CREATE OR REPLACE FUNCTION reject_stock_movement_mutation() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'stock_movements is append-only; record a compensating ADJUST movement instead';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_stock_movements_immutable
    BEFORE UPDATE OR DELETE ON stock_movements
    FOR EACH ROW EXECUTE FUNCTION reject_stock_movement_mutation();
